### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by GarryFirst-cripto** [GarryFirst-cripto/us_president_resume#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by GarrySecond-cripto** [comment]
<div class="info">
                          <img class="abzImg" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Joe_Biden_at_Age_10.jpg/170px-Joe_Biden_at_Age_10.jpg" alt="Young Biden">
                          <p class="abzs" ><bk>J</bk>oseph Robinette Biden Jr. was born November 20, 1942, at St. Mary's Hospital in Scranton, Pennsylvania, to Catherine Eugenia "Jean" Biden (née Finnegan) and Joseph Robinette Biden Sr.
                            The oldest child in a Catholic family, he has a sister, Valerie, and two brothers, Francis and James. Jean was of Irish descent, while Joseph Sr. had English, French, and Irish ancestry.<br>
                            Biden's father was initially wealthy but suffered financial setbacks around the time Biden was born, and for several years the family lived with Biden's maternal grandparents. Scranton fell into economic decline
                             during the 1950s and Biden's father could not find steady work. Beginning in 1953, the family lived in an apartment in Claymont, Delaware, then moved to a house in Wilmington, Delaware. Biden Sr. later 
                             became a successful used car salesman, maintaining the family in a middle-class lifestyle.<br>
                            At Archmere Academy in Claymont, Biden was a standout halfback and wide receiver on the high school football team; he also played baseball. Though a poor student, he was class president in his junior and senior
                             years. He graduated in 1961. At the University of Delaware in Newark, Biden briefly played freshman football and earned a Bachelor of Arts degree in 1965 with a double major in history and political science,
                              and a minor in English. He had a C average and ranked 506th in his class of 688.</p>
                        </div>

**Comment by GarrySecond-cripto** [comment]
<div class="sixteen wide column">
                    <h2 align="center">US President Résumé</h2>
                    <p align="justify">&mdash; Biden was elected the 46th president of the United States in November 2020. He defeated the incumbent, Donald Trump, becoming the first candidate to defeat 
                      a sitting president since Bill Clinton defeated George H. W. Bush in 1992. He is the second non-incumbent vice president (after Richard Nixon in 1968) to be elected president. He 
                      is also expected to become the oldest president, as well as the first president whose home state is Delaware (although he was born in Pennsylvania), and the second Catholic 
                      president after John F. Kennedy.</p>
                  </div>
