### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by GarryFirst-cripto** [GarryFirst-cripto/us_president_resume#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by GarrySecond-cripto** [comment]
<div class="sixteen wide column">
                    <h1 class="name">Joe Biden</h1>
                    <div class="job" style="margin-bottom: 10px">46th President of the United States</div>
                    <ul class="contacts">
                      <li>
                        <a href="https://www.facebook.com//joebiden/" class="facebook" style="display: flex; align-items: center">
                          <img src="https://cdn3.iconfinder.com/data/icons/material-design-social-icons/152/facebook_icon-512.png" width="24" height="24" style="margin-right: 5px">
                          <span>Joe Biden's Facebook</span>
                        </a>
                      </li>
                      <li>
                        <a href="https://twitter.com/joebiden" class="mail" style="display: flex; align-items: center">
                          <img src="https://webstockreview.net/images/twitter-icon-png-1.png" width="24" height="24" style="margin-right: 5px">
                          <span>Joe Biden's Twiter</span>
                        </a>
                      </li>
                      <li>
                        <a href="https://en.wikipedia.org/wiki/Joe_Biden" rel="author" class="skype" style="display: flex; align-items: center">
                          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0hujHU3GMWgHB0VR8Vgn75MtiaEPeb2Sdtw&usqp=CAU" width="20" height="24" style="margin-right: 5px">
                          <span>Wikipedia</span>
                        </a>
                      </li>
                      <li>
                        <a href="https://www.whitehouse.gov/get-involved/write-or-call/" class="phone" style="display: flex; align-items: center">
                          <img src="https://cdn3.iconfinder.com/data/icons/july-4th/110/white_house_american_america_us_independence_president-2-512.png" width="36" height="24" style="margin-right: 5px">
                          <span>Write or Call</span>
                        </a>
                      </li>
                    </ul>
                  </div>
