### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by GarryFirst-cripto** [GarryFirst-cripto/us_president_resume#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by GarrySecond-cripto** [comment]
<li class="itemList"><a href="#" onclick="sublistclick(event)"> Speculation and announcement</a>
                        <div class="info">
                          <img class="abzImg" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Joe_Biden_kickoff_rally_May_2019.jpg/220px-Joe_Biden_kickoff_rally_May_2019.jpg" alt="President">
                          <p class="abzs"><bk>B</bk>etween 2016 and 2019, media outlets often mentioned Biden as a likely candidate for president in 2020.[300] When asked if he would run, he gave varied and ambivalent answers, 
                            saying "never say never". At one point he suggested he did not see a scenario where he would run again, but a few days later, he said, "I'll run if I can walk." A political action committee known as 
                            Time for Biden was formed in January 2018, seeking Biden's entry into the race.<br>
                            Biden said he would decide whether to run or not by January 2019, but made no announcement at that time. Friends said he was "very close to saying yes" but was concerned about the effect another presidential 
                            run could have on his family and reputation, as well as fundraising struggles and perceptions about his age and relative centrism. On the other hand, he said he was prompted to run by his "sense of duty", 
                            offense at the Trump presidency, what he felt was a lack of foreign policy experience among other Democratic hopefuls, and his desire to foster "bridge-building progressivism" in the party. He launched 
                            his campaign on April 25, 2019.</p>
                        </div>
                      </li>
                      <li class="itemList"><a href="#" onclick="sublistclick(event)"> Campaign</a>
                        <div class="info">
                          <img class="abzImg" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Joe_Biden_kickoff_rally_May_2019.jpg/220px-Joe_Biden_kickoff_rally_May_2019.jpg" alt="President">
                          <p class="abzs"><bk>T</bk>hroughout 2019, Biden stayed generally ahead of other Democrats in national polls. Despite this, he finished fourth in the Iowa caucuses, and eight days later, fifth in the New 
                            Hampshire primary. He performed better in the Nevada caucuses, reaching the 15% required for delegates, but still was behind Bernie Sanders by 21.6 percentage points. Making strong appeals to black voters 
                            on the campaign trail and in the South Carolina debate, Biden won the South Carolina primary by more than 28 points. After the withdrawals and subsequent endorsements of candidates Pete Buttigieg and
                            Amy Klobuchar, he made large gains in the March 3 Super Tuesday primary elections. Biden won 18 of the next 26 contests, including Alabama, Arkansas, Maine, Massachusetts, Minnesota, North Carolina, 
                            Oklahoma, Tennessee, Texas, and Virginia, putting him in the lead overall.[325] Elizabeth Warren and Mike Bloomberg soon dropped out, and Biden expanded his lead with victories over Sanders in four 
                            states (Idaho, Michigan, Mississippi, and Missouri) on March 10.<br>
                            When Sanders suspended his campaign on April 8, 2020, Biden became the Democratic Party's presumptive nominee for president.</p>
                        </div>
                      </li>
