### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by GarryFirst-cripto** [GarryFirst-cripto/us_president_resume#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by GarrySecond-cripto** [comment]
<div class="avatar-wrapper">
                  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Joe_Biden_official_portrait_2013_cropped.jpg/220px-Joe_Biden_official_portrait_2013_cropped.jpg" alt="Biden_official_portrait">
                </div>

**Comment by GarryFirst-cripto** [comment]
Perfectly well !
